#pragma once

#define SOFT_SERIAL_PIN D0
#define USE_SERIAL

#define MASTER_RIGHT

#define UNICODE_SELECTED_MODES UC_LNX
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
#define DISABLE_LEAD

#define TAPPING_TERM 220
#define QUICK_TAP_TERM 0
#define FLOW_TAP_TERM 150
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_INVERT_ON_SHIFT
